"""initial

Revision ID: 04915bf2fada
Revises: 
Create Date: 2021-05-24 16:14:49.695486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04915bf2fada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('autobase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('consumer', sa.String(length=80), nullable=True),
    sa.Column('secret', sa.String(length=80), nullable=True),
    sa.Column('CONSUMER_KEY', sa.String(length=80), nullable=True),
    sa.Column('CONSUMER_SECRET', sa.String(length=80), nullable=True),
    sa.Column('ACCESS_KEY', sa.String(length=80), nullable=True),
    sa.Column('ACCESS_SECRET', sa.String(length=80), nullable=True),
    sa.Column('ENV_NAME', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autobase_name'), 'autobase', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autobase_name'), table_name='autobase')
    op.drop_table('autobase')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
